language:
  - python
install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
env:
  global:
    - SERMIN_TEST_MODE=full
script:
  - flake8 && sudo python setup.py nosetests -s -vv
